/* TBG Walk-Ins — route + lead data.
   Generated from the June cold-approach campaign + warm replies. This file is the
   portable source of truth: the web app reads window.TBG, and the same records live
   in the Notion CRM ("TBG Walk-Ins — Leads & Visits") so future tools can share them.
   Addresses verified June 2026; "call ahead" = PO-box / home office, confirm first. */
window.TBG = {
  generated: "2026-06-07",
  dayNotes: {
    Mon: "<b>Bellevue loop — two HOT leads anchor today.</b> Call Taylor Morrison (Pete Lymberis / Alice Knudson) first to lock a real meeting — they invited you to the office and floated Tue Jun 2; confirm that happened or rebook. At The Custom Home Company, coordinate with Geronimo: the MV3 bid is due <b>today (6/8)</b> — your visit is to meet Nariko & reinforce, not renegotiate.",
    Tue: "<b>Kirkland → Redmond.</b> All cold intros. Goal each stop: get on the framing bid list, leave a card, and walk out with the estimator's name + email.",
    Wed: "<b>Seattle. ★ 2:00 PM Coastline Church SITE WALK — 2420 2nd Ave.</b> This is the week's priority — meet Bryon Atterberry in person (RFIs due 6/11, bids 6/12). Work the morning Seattle stops around it.",
    Thu: "<b>North loop: Shoreline → Lynnwood → Everett → Snohomish.</b> Finish at CPM's HQ in Snohomish to reinforce the Coastline relationship face-to-face.",
    Fri: "<b>SLU / Georgetown → Issaquah.</b> Call Jordan Valente before driving (PO-box only). Keep the afternoon open for follow-ups with anyone you met Mon–Thu."
  },
  companies: [
    /* ===================== MONDAY — Bellevue ===================== */
    { id:"customhc", day:"Mon", order:1, priority:"P1", priorityLabel:"P1 · Hot", region:"Eastside", status:"Warm",
      company:"The Custom Home Company", contact:"Nariko Kawashima", contactTitle:"VP Purchasing & Procurement",
      address:"40 Lake Bellevue Dr, Ste 169, Bellevue, WA 98005", phone:"(425) 740-9501",
      project:"MV3 Emerald Family Trust — itemized framing bid due Mon 6/8",
      nextStep:"Meet Nariko in person, confirm scope, reinforce. Don't step on Geronimo's active bid.",
      opener:"Hi Nariko, I'm Rafael with Twin Brothers Group — Geronimo's getting your MV3 itemized numbers over today. I was in the area and wanted to put a face to the name and make sure you have everything you need from us.",
      intel:"Active bid: labor + nails/screws/glue + equipment, itemized per line. They want documented project photos. Bellevue-based like us." },
    { id:"taylormorrison", day:"Mon", order:2, priority:"P1", priorityLabel:"P1 · Hot", region:"Eastside", status:"Warm",
      company:"Taylor Morrison (PNW Division)", contact:"Pete Lymberis / Alice Knudson", contactTitle:"Div. President / VP Purchasing",
      address:"13810 SE Eastgate Way, Ste 410, Bellevue, WA 98005", phone:"(425) 586-7700",
      project:"TerraLuxe townhomes, Sammamish (Fall 2026) — they invited you to the office",
      nextStep:"CALL Pete/Alice first to lock the meeting they offered. Walk in only to confirm a time if no answer.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Pete invited us to come meet the team after we reached out on TerraLuxe — I wanted to introduce myself and get on the calendar with purchasing.",
      intel:"HOTTEST lead. Pete (Div Pres) replied warmly, looped in Alice Knudson (VP Purchasing) who proposed Tue Jun 2 @ 2:30. They pay on time, want quality framers. Confirm whether that meeting happened." },
    { id:"mirra", day:"Mon", order:3, priority:"P2", priorityLabel:"P2 · Warm", region:"Eastside", status:"Cold-Emailed",
      company:"Mirra Homes", contact:"", contactTitle:"",
      address:"11624 SE 5th St, Ste 210, Bellevue, WA 98005", phone:"(425) 559-2380",
      project:"Townhome communities in Kirkland — multi-unit ground-up",
      nextStep:"Intro, get on bid list, get estimator name/email.",
      opener:"Hi, Rafael with Twin Brothers Group, a Bellevue framing sub. I saw you're building townhome communities up in Kirkland — multi-unit is exactly our lane. Who handles your framing bids?",
      intel:"Cold-emailed 6/5 ('framing for townhomes'). Multi-unit volume = good fit for in-house crews." },
    { id:"chaffey", day:"Mon", order:4, priority:"P2", priorityLabel:"P2 · Warm", region:"Eastside", status:"Cold-Emailed",
      company:"Chaffey Construction", contact:"Rick", contactTitle:"",
      address:"915 118th Ave SE, Ste 325, Bellevue, WA 98005", phone:"(425) 452-1800",
      project:"Bellevue waterfront & Meydenbauer Bay corridor builds",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, is Rick around? Rafael with Twin Brothers Group framing. We've been watching your Bellevue waterfront work — serious builds that need serious framing. Wanted to introduce our in-house crews.",
      intel:"Cold-emailed 6/5 ('framing crews eastside'). High-end Bellevue GC." },
    { id:"damskov", day:"Mon", order:5, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Damskov Construction", contact:"Cameron", contactTitle:"",
      address:"1940 124th Ave NE, Ste A107, Bellevue, WA 98005", phone:"(425) 454-8059",
      project:"Clyde Hill contemporary & Grapeview waterfront — luxury customs, King & Snohomish",
      nextStep:"Intro, leave card, get on bid list.",
      opener:"Hi Cameron, Rafael with Twin Brothers Group framing. Saw your Clyde Hill and Grapeview work — sharp stuff. We frame luxury customs across the same counties and wanted to introduce ourselves.",
      intel:"Cold-emailed 6/4 ('crew openings')." },
    { id:"gallagher", day:"Mon", order:6, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Gallagher Construction", contact:"Sean", contactTitle:"",
      address:"12835 Bel-Red Rd, Ste 320, Bellevue, WA 98005", phone:"(425) 748-4468",
      project:"Bellevue design-build — whole-house remodels & major additions",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, looking for Sean — Rafael with Twin Brothers Group framing. Your Bellevue design-build work needs framing crews that handle structural complexity without holding the schedule. That's us.",
      intel:"Cold-emailed 6/5 ('framing partner bellevue'). Site may redirect to designremodel.com — verify suite." },

    /* ===================== TUESDAY — Kirkland / Redmond ===================== */
    { id:"compass", day:"Tue", order:1, priority:"P2", priorityLabel:"P2 · Warm", region:"Eastside", status:"Cold-Emailed",
      company:"Compass Construction (Compass GC)", contact:"", contactTitle:"",
      address:"11332 NE 122nd Way, Ste 350, Kirkland, WA 98034", phone:"(206) 320-8741",
      project:"Trace 4001 (191 units, Othello) + LIZA (207 units) — full wood-frame pipeline",
      nextStep:"Intro, get on bid list — this is a strong volume target.",
      opener:"Hi, Rafael with Twin Brothers Group framing. You've got Trace 4001 and LIZA running — ~400 units of wood-frame. We're a Bellevue framing sub with in-house crews built for exactly that volume.",
      intel:"Cold-emailed 6/4 ('framing crews available'). Biggest near-term pipeline on the list." },
    { id:"enfort", day:"Tue", order:2, priority:"P2", priorityLabel:"P2 · Warm", region:"Eastside", status:"Cold-Emailed",
      company:"Enfort Homes", contact:"Shad", contactTitle:"",
      address:"733 7th Ave, Ste 200, Kirkland, WA 98033", phone:"(425) 312-3678",
      project:"19 homes — Nighthawk, Copeland Cove, Dorsett & Huntley plats",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, is Shad in? Rafael with Twin Brothers Group framing. With 19 homes across your Kirkland plats you need crews that keep pace without sacrificing quality — wanted to introduce ours.",
      intel:"Cold-emailed 6/5 ('framing capacity kirkland')." },
    { id:"mainstreet", day:"Tue", order:3, priority:"P2", priorityLabel:"P2 · Warm", region:"Eastside", status:"Cold-Emailed",
      company:"MainStreet Property Group", contact:"", contactTitle:"",
      address:"5808 Lake Washington Blvd NE, Ste 203, Kirkland, WA 98033", phone:"(425) 298-0240",
      project:"Mixed-use landmark projects across Kirkland & the Eastside",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. MainStreet's Kirkland mixed-use work sets a high bar for coordination from the framing stage forward — that's where we shine. Who runs your trade partners?",
      intel:"Cold-emailed 6/5 ('your kirkland builds')." },
    { id:"roberts", day:"Tue", order:4, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Roberts Group", contact:"", contactTitle:"",
      address:"5914 Lake Washington Blvd NE, Kirkland, WA 98033", phone:"(425) 483-0234",
      project:"Custom work along the Lake Washington corridor, Kirkland",
      nextStep:"Intro, leave card.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Your Lake Washington custom work is the kind that demands precision framing — wanted to introduce our in-house crews.",
      intel:"Cold-emailed 6/5 ('custom framing kirkland'). Two doors down from MainStreet — easy combo." },
    { id:"rdhomes", day:"Tue", order:5, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"RD Homes", contact:"", contactTitle:"",
      address:"1320 Market St, Kirkland, WA 98033", phone:"(206) 697-2949",
      project:"Energy-efficient spec homes across Kirkland & the Eastside (since 2002)",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. I've seen your energy-efficient spec homes around Kirkland — clean, consistent builds. We'd like to be on your framing bid list.",
      intel:"Cold-emailed 6/5 ('wood frame crews'). Confirm suite at front desk (registered addr differs)." },
    { id:"lochwood", day:"Tue", order:6, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Lochwood-Lozier Custom Homes", contact:"", contactTitle:"",
      address:"8708 152nd Ave NE, Redmond, WA 98052", phone:"(425) 576-9200",
      project:"40+ yrs luxury customs — Medina, Clyde Hill, Mercer Island",
      nextStep:"Intro, leave card with marketing/estimating.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Forty-plus years of Eastside luxury customs means the framing has to be flawless — that's the standard we hold. Wanted to introduce ourselves.",
      intel:"Cold-emailed 6/4 ('framing team'). Office is in Redmond (not Woodinville)." },

    /* ===================== WEDNESDAY — Seattle (CPM site walk 2pm) ===================== */
    { id:"dovetail", day:"Wed", order:1, priority:"P2", priorityLabel:"P2 · Warm", region:"Seattle", status:"Cold-Emailed",
      company:"Dovetail General Contractors", contact:"", contactTitle:"",
      address:"1143 NW 45th St, Seattle, WA 98107", phone:"(206) 545-0722",
      project:"Commercial & residential across Seattle — craftsmanship-driven GC",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Dovetail's the kind of GC where framing quality shows in the finished product — wanted to introduce our in-house crews and get on your bid list.",
      intel:"Cold-emailed 6/5 ('framing for dovetail'). Ballard/Fremont — first stop, then head south." },
    { id:"pillar", day:"Wed", order:2, priority:"P2", priorityLabel:"P2 · Warm", region:"Seattle", status:"Cold-Emailed",
      company:"Pillar Properties", contact:"", contactTitle:"",
      address:"1938 Fairview Ave E, Ste 300, Seattle, WA 98102", phone:"(206) 676-5300",
      project:"2,100+ units across Seattle + 10 projects on the boards",
      nextStep:"Intro, find the right development/construction contact.",
      opener:"Hi, Rafael with Twin Brothers Group framing. 2,100+ units and ten more on the boards — that volume needs a framing crew that can keep up. We're Bellevue-based with in-house crews. Who handles trade partners?",
      intel:"Cold-emailed 6/5 ('your seattle pipeline'). Large pipeline." },
    { id:"holland", day:"Wed", order:3, priority:"P2", priorityLabel:"P2 · Warm", region:"Seattle", status:"Cold-Emailed",
      company:"Holland Partner Group", contact:"", contactTitle:"",
      address:"1225 Dexter Ave N, Seattle, WA 98109", phone:"(206) 217-0042",
      project:"Multifamily communities across the PNW",
      nextStep:"Intro, get on bid list. (Seattle office; HQ is Vancouver WA.)",
      opener:"Hi, Rafael with Twin Brothers Group framing. Holland's PNW multifamily work needs subs who deliver consistent quality at scale — that's our lane. Wanted to connect with whoever runs framing trade partners here.",
      intel:"Cold-emailed 6/5 ('wood-frame crews pnw'). Confirm Seattle office handles local purchasing." },
    { id:"spectrum", day:"Wed", order:4, priority:"P2", priorityLabel:"P2 · Warm", region:"Seattle", status:"Cold-Emailed",
      company:"Spectrum Development Solutions", contact:"", contactTitle:"",
      address:"101 Stewart St, Ste 1000, Seattle, WA 98101", phone:"(206) 628-3150",
      project:"Multifamily / mixed-use / community-driven development, Seattle",
      nextStep:"Intro, get on bid list. Downtown — near the 2pm site walk.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Spectrum's mixed-use projects take a serious approach from concept through delivery — framing included. Wanted to introduce our crews.",
      intel:"Cold-emailed 6/5 ('framing your projects'). Downtown, walkable to the Coastline site walk." },
    { id:"cpm-sitewalk", day:"Wed", order:5, priority:"P1", priorityLabel:"P1 · Hot", region:"Seattle", status:"Warm",
      company:"★ CPM — Coastline Church SITE WALK", contact:"Bryon Atterberry", contactTitle:"Lead Estimator",
      address:"2420 2nd Ave, Seattle, WA 98121", phone:"(206) 498-3207",
      project:"Coastline Church — framing labor: new walls, roof repairs, structural upgrades",
      nextStep:"BE THERE 2:00 PM. Meet Bryon in person. RFIs due 6/11 1pm, bids due 6/12 5pm.",
      opener:"Bryon — Rafael from Twin Brothers Group, good to meet you in person. We're confirming intent to bid on the framing labor. Walk me through the structural scope so our number's tight.",
      intel:"They named TBG a PREFERRED contractor. Site walk 6.10 @ 2pm. Email RFIs to bryon@cpmnw.com (no calls), bids to bids@cpmnw.com. Start late June/early July." },
    { id:"edge", day:"Wed", order:6, priority:"P3", priorityLabel:"P3 · Cold", region:"Seattle", status:"Cold-Emailed",
      company:"Edge Developers", contact:"", contactTitle:"",
      address:"1225 S Weller St, Ste 555, Seattle, WA 98144", phone:"(206) 900-8605",
      project:"250+ units mixed-use infill across the Puget Sound",
      nextStep:"Intro if time after the site walk. (Marpac is in the same building — Ste 500.)",
      opener:"Hi, Rafael with Twin Brothers Group framing. Edge's infill track record — 250+ units on tight urban sites — is exactly the work our in-house crews are built for. Wanted to get on your bid list.",
      intel:"Cold-emailed 6/5 ('your infill projects'). Same building as Marpac (Ste 500) — knock both." },

    /* ===================== THURSDAY — North / Snohomish ===================== */
    { id:"irons", day:"Thu", order:1, priority:"P3", priorityLabel:"P3 · Cold", region:"Shoreline/North", status:"Cold-Emailed",
      company:"Irons Brothers Construction", contact:"", contactTitle:"",
      address:"14926 Aurora Ave N, Shoreline, WA 98133", phone:"(206) 306-7767",
      project:"New Design Build Center on Aurora — 25+ yrs in Shoreline, expanding",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Congrats on the new Design Build Center — with that growth you'll want reliable framing crews on call. Wanted to introduce ours.",
      intel:"Cold-emailed 6/5 ('framing crews available'). First north stop." },
    { id:"msr", day:"Thu", order:2, priority:"P2", priorityLabel:"P2 · Warm", region:"Snohomish", status:"Cold-Emailed",
      company:"MSR Communities", contact:"Stesha", contactTitle:"",
      address:"806 164th St SW, Bldg A, 2nd Fl, Lynnwood, WA 98037", phone:"(425) 300-2677",
      project:"Hidden Meadow5 — 5 luxury single-family, Kenmore (online this summer)",
      nextStep:"Intro, get on bid list for Hidden Meadow + pipeline.",
      opener:"Hi, looking for Stesha — Rafael with Twin Brothers Group framing. Hidden Meadow5 is a tight scope where framing quality shows in every wall and roofline. We'd like to bid it.",
      intel:"Cold-emailed 6/4 ('framing for hidden meadow')." },
    { id:"rgn", day:"Thu", order:3, priority:"P3", priorityLabel:"P3 · Cold", region:"Snohomish", status:"Cold-Emailed",
      company:"RGN Construction", contact:"Rich", contactTitle:"",
      address:"16417 7th Pl W, Lynnwood, WA 98037", phone:"(206) 632-7031",
      project:"71+ permitted projects, 25 yrs — King, Snohomish & Island Counties",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, is Rich in? Rafael with Twin Brothers Group framing. 71+ permitted projects out of Lynnwood is a serious operation — wanted to introduce our crews and get on your framing list.",
      intel:"Cold-emailed 6/5 ('framing for rgn')." },
    { id:"united", day:"Thu", order:4, priority:"P2", priorityLabel:"P2 · Warm", region:"Snohomish", status:"Cold-Emailed",
      company:"United Seattle", contact:"Victor", contactTitle:"",
      address:"1010 SE Everett Mall Way, Ste 100, Everett, WA 98208", phone:"(425) 521-7916",
      project:"Design-build + ADU expansion, 300+ team, Everett & Puget Sound",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. A 300-person design-build operation moving on ADUs and customs needs subs who keep pace — that's us. Who runs your framing bids?",
      intel:"Cold-emailed 6/5 ('framing partner everett')." },
    { id:"gamut360", day:"Thu", order:5, priority:"P3", priorityLabel:"P3 · Cold", region:"Snohomish", status:"Cold-Emailed",
      company:"Gamut360", contact:"", contactTitle:"",
      address:"3726 Broadway, Ste 301, Everett, WA 98201", phone:"(425) 212-2210",
      project:"Townhome work across Snohomish County (since 2003)",
      nextStep:"CALL to confirm office is open before stopping.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Your townhome volume across Snohomish needs framers who keep up without callbacks. Wanted to introduce ours.",
      intel:"Cold-emailed 6/4 ('crew availability'). One directory flags 'closed' — phone-confirm first." },
    { id:"cpm-hq", day:"Thu", order:6, priority:"P1", priorityLabel:"P1 · Hot", region:"Snohomish", status:"Warm",
      company:"CPM Construction (HQ)", contact:"Bryon Atterberry", contactTitle:"Lead Estimator",
      address:"1509 Bonneville Ave, Ste A, Snohomish, WA 98290", phone:"(360) 863-6705",
      project:"Reinforce the Coastline Church relationship at their office",
      nextStep:"Drop by to thank Bryon, confirm bid progress, ask what else is in their pipeline.",
      opener:"Hi, Rafael from Twin Brothers Group — I was up north and wanted to stop in. Appreciate you having us on Coastline as a preferred trade. What else do you have coming up we should be bidding?",
      intel:"Only visit if the Wed site walk went well. Caps off the north loop. Office is Snohomish, project is downtown Seattle." },

    /* ===================== FRIDAY — Georgetown / SLU → Issaquah + flex ===================== */
    { id:"toth", day:"Fri", order:1, priority:"P3", priorityLabel:"P3 · Cold", region:"Seattle", status:"Cold-Emailed",
      company:"Toth Construction", contact:"", contactTitle:"",
      address:"220 S River St, Seattle, WA 98108", phone:"(206) 242-9093",
      project:"50 yrs in Seattle — Broadmoor, Three Tree Point, Windermere",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Fifty years and a portfolio like Broadmoor doesn't happen without demanding the best from every trade — we'd like to be your framing crew.",
      intel:"Cold-emailed 6/4 ('framing availability'). Georgetown." },
    { id:"scc", day:"Fri", order:2, priority:"P3", priorityLabel:"P3 · Cold", region:"Seattle", status:"Cold-Emailed",
      company:"Seattle Custom Contractors", contact:"Adam", contactTitle:"",
      address:"2144 Westlake Ave N, Ste E, Seattle, WA 98109", phone:"(206) 795-9581",
      project:"Custom work around the Eastside / Redmond",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, looking for Adam — Rafael with Twin Brothers Group framing. We're Bellevue-based and frame for builders all over Redmond and Kirkland. Wanted to introduce ourselves.",
      intel:"Cold-emailed 6/4 ('framing sub redmond'). South Lake Union." },
    { id:"trailside", day:"Fri", order:3, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Trailside Homes", contact:"", contactTitle:"",
      address:"405 NW Gilman Blvd, Ste 102, Issaquah, WA 98027", phone:"(206) 388-3121",
      project:"Ederra (Cle Elum) + Finn Hill short plat (Issaquah)",
      nextStep:"Intro, get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Saw Ederra's moving and you've got Finn Hill coming in Issaquah — community builds with that range keep a framing schedule tight. We'd like to bid.",
      intel:"Cold-emailed 6/4 ('framing crews'). Use the Issaquah metro office (HQ is Cle Elum)." },
    { id:"jordanvalente", day:"Fri", order:4, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Jordan Valente", contact:"Jordan Valente", contactTitle:"",
      address:"Issaquah, WA 98027 — PO Box only, CALL FIRST", phone:"(425) 651-4059",
      project:"30 yrs, NKBA awards, Luxe Gold List — high-end Issaquah",
      nextStep:"CALL before driving — no public street office.",
      opener:"Hi Jordan, Rafael with Twin Brothers Group framing. 30 years and a Luxe Gold List — you don't cut corners and neither do we. I'm in Issaquah today; any chance to swing by and introduce myself?",
      intel:"Cold-emailed 6/5 ('framing sub issaquah'). PO Box 671 only — phone first." },
    { id:"emerald", day:"Fri", order:5, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Emerald City Build", contact:"", contactTitle:"",
      address:"2571 152nd Ave NE, Ste 15B, Redmond, WA 98007", phone:"(425) 502-8174",
      project:"Custom builds & DADU work, Seattle–Redmond",
      nextStep:"Intro on the way back through Redmond. Get on bid list.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Your custom and DADU mix between Seattle and Redmond keeps a framing schedule tight — wanted to introduce our in-house crews.",
      intel:"Cold-emailed 6/4 ('wood frame'). Redmond — catch on the return leg." },

    /* ===================== UNSCHEDULED — backlog / call-ahead / South day trip ===================== */
    { id:"everton", day:"Unscheduled", order:1, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Cold-Emailed",
      company:"Everton Homes", contact:"", contactTitle:"",
      address:"2300 130th Ave NE, Bldg A, Ste 104, Bellevue, WA 98005 (verify — relocating)", phone:"(425) 202-7728",
      project:"Luxury builds across Bellevue, Kirkland, Redmond",
      nextStep:"Verify current address (reportedly relocating late 2025), then intro.",
      opener:"Hi, Rafael with Twin Brothers Group framing. We work the same Bellevue–Kirkland–Redmond neighborhoods daily and wanted to introduce our crews for your luxury builds.",
      intel:"Cold-emailed 6/4 ('framing luxury eastside'). Confirm office before driving." },
    { id:"evergreenpoint", day:"Unscheduled", order:2, priority:"P3", priorityLabel:"P3 · Cold", region:"Eastside", status:"Replied?",
      company:"Evergreen Point / EPGroup", contact:"", contactTitle:"",
      address:"PO Box 241, Medina, WA 98039 — no public office, CALL FIRST", phone:"(425) 646-3838",
      project:"Cerasa (155 units, Bellevue) + The Line (241) + Leeway coming up",
      nextStep:"CALL — strong multifamily pipeline but no walk-in address.",
      opener:"Hi, Rafael with Twin Brothers Group framing. With Leeway coming up after Cerasa and The Line, you'll be lining up framing — we're Bellevue-based with in-house crews and want to bid.",
      intel:"Cold-emailed 6/5 ('leeway framing'). PO box only; phone to find office." },
    { id:"absher", day:"Unscheduled", order:3, priority:"P3", priorityLabel:"P3 · Cold", region:"Pierce/South", status:"Cold-Emailed",
      company:"Absher Construction", contact:"", contactTitle:"",
      address:"310 120th Ave NE, Ste 100, Bellevue, WA 98005 (Bellevue office) — HQ 1001 Shaw Rd, Puyallup", phone:"(253) 845-9544",
      project:"38+ projects in Puyallup — multi-unit housing, Pierce County",
      nextStep:"Has a BELLEVUE office — slot into an Eastside day if pipeline justifies.",
      opener:"Hi, Rafael with Twin Brothers Group framing. We've watched Absher build across Pierce for years — your multi-unit work is exactly our lane. Wanted to introduce ourselves.",
      intel:"Cold-emailed 6/4 ('framing for multi-unit'). Bellevue office makes this an easy add." },
    { id:"colvos", day:"Unscheduled", order:4, priority:"P3", priorityLabel:"P3 · Cold", region:"Pierce/South", status:"Cold-Emailed",
      company:"Colvos Construction", contact:"", contactTitle:"",
      address:"711 Court C, Tacoma, WA 98402", phone:"(253) 844-4640",
      project:"Multifamily / mixed-use / hospitality, Tacoma–Bellevue",
      nextStep:"Group into a South day trip with Omega/Noffke/Steve Jensen.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Colvos runs multifamily and hospitality across a wide range — that needs subs who perform anywhere. We'd like to bid your framing.",
      intel:"Cold-emailed 6/5 ('multifamily framing partner')." },
    { id:"omega", day:"Unscheduled", order:5, priority:"P3", priorityLabel:"P3 · Cold", region:"Pierce/South", status:"Cold-Emailed",
      company:"Omega Custom Homes", contact:"Ian", contactTitle:"",
      address:"12815 Canyon Rd E, Ste H, Puyallup, WA 98373", phone:"(253) 446-1100",
      project:"Full-service design-build — King, Pierce, Thurston",
      nextStep:"South day trip.",
      opener:"Hi, looking for Ian — Rafael with Twin Brothers Group framing. Your design-build approach values partners who execute — that's how we run framing. Wanted to introduce ourselves.",
      intel:"Cold-emailed 6/5 ('puyallup framing crew')." },
    { id:"noffke", day:"Unscheduled", order:6, priority:"P3", priorityLabel:"P3 · Cold", region:"Pierce/South", status:"Cold-Emailed",
      company:"Noffke Homes", contact:"", contactTitle:"",
      address:"21280 SR-410 E, Bonney Lake, WA 98391", phone:"(253) 299-4076",
      project:"Tehaleh master-planned community + Blaine & Ellensburg expansion",
      nextStep:"South day trip.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Tehaleh's one of the strongest master-planned communities in Pierce right now — that momentum needs framing crews that scale. We'd like to bid.",
      intel:"Cold-emailed 6/5 ('framing at tehaleh')." },
    { id:"stevejensen", day:"Unscheduled", order:7, priority:"P3", priorityLabel:"P3 · Cold", region:"Pierce/South", status:"Cold-Emailed",
      company:"Steve Jensen Homes", contact:"", contactTitle:"",
      address:"1230 Fryar Ave, Sumner, WA 98390", phone:"(253) 891-8020",
      project:"40+ yrs luxury customs across the Puget Sound",
      nextStep:"South day trip.",
      opener:"Hi, Rafael with Twin Brothers Group framing. 40+ years of luxury customs means you know how much framing quality matters in high-end work — that's the standard we hold.",
      intel:"Cold-emailed 6/5 ('luxury framing crews')." },
    { id:"chandler", day:"Unscheduled", order:8, priority:"P3", priorityLabel:"P3 · Cold", region:"Pierce/South", status:"Cold-Emailed",
      company:"Chandler Custom Homes", contact:"Erin", contactTitle:"",
      address:"7506 147th Ave E, Sumner, WA 98390 (appears residential — call first)", phone:"(253) 682-8667",
      project:"Design-build across Pierce — Sumner, Gig Harbor, Black Diamond",
      nextStep:"CALL first (home office). South day trip.",
      opener:"Hi Erin, Rafael with Twin Brothers Group framing. Your Pierce County design-build work cares about details from concept to finishes — framing included. Wanted to introduce ourselves.",
      intel:"Cold-emailed 6/5 ('pierce county framing'). Likely home office." },
    { id:"kurkov", day:"Unscheduled", order:9, priority:"P3", priorityLabel:"P3 · Cold", region:"Pierce/South", status:"Cold-Emailed",
      company:"Kurkov Construction", contact:"Paul", contactTitle:"",
      address:"PO Box 833, Graham, WA 98338 — no public office, CALL FIRST", phone:"(253) 732-2382",
      project:"Custom + multi-family, Pierce — top 5% WA contractors (BuildZoom)",
      nextStep:"CALL — PO box only.",
      opener:"Hi Paul, Rafael with Twin Brothers Group framing. Top 5% of WA contractors speaks for itself — we'd like to be your framing crew on the custom and multi-family work.",
      intel:"Cold-emailed 6/5 ('framing for kurkov'). PO box / residential." },
    { id:"nate", day:"Unscheduled", order:10, priority:"P3", priorityLabel:"P3 · Cold", region:"Snohomish", status:"Cold-Emailed",
      company:"NATE Construction", contact:"", contactTitle:"",
      address:"18616 109th Ave SE, Snohomish, WA 98296 (appears residential — call first)", phone:"(206) 307-6512",
      project:"Custom homes across Snohomish + light commercial",
      nextStep:"CALL first (home office). Add to a north loop.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Custom homes across Snohomish plus light commercial — we frame both. Wanted to introduce our crews.",
      intel:"Cold-emailed 6/5 ('snohomish framing crews'). Likely home office." },
    { id:"acme", day:"Unscheduled", order:11, priority:"P3", priorityLabel:"P3 · Cold", region:"Snohomish", status:"Cold-Emailed",
      company:"Acme Homes WA", contact:"", contactTitle:"",
      address:"10211 180th St SE, Snohomish, WA 98296 (appears residential — call first)", phone:"(425) 903-1453",
      project:"Valley Vista Estates (Monroe) + Cottonwood Creek (Stanwood)",
      nextStep:"CALL first. Add to a north loop.",
      opener:"Hi, Rafael with Twin Brothers Group framing. Valley Vista and Cottonwood Creek are a solid Snohomish pipeline — we'd like to bid your framing.",
      intel:"Cold-emailed 6/5 ('framing for valley vista'). Likely home office." },
    { id:"craigreimer", day:"Unscheduled", order:12, priority:"P3", priorityLabel:"P3 · Cold", region:"Snohomish", status:"Cold-Emailed",
      company:"Craig Reimer Custom Homes", contact:"Craig", contactTitle:"",
      address:"18607 Olympic View Dr, Edmonds, WA 98020 (appears residential — call first)", phone:"(206) 227-4682",
      project:"Custom work in Edmonds & Suncadia — precision reputation",
      nextStep:"CALL first (home office). Add to a north loop.",
      opener:"Hi Craig, Rafael with Twin Brothers Group framing. Your Edmonds and Suncadia work has a reputation for precision — that starts with the framing. Wanted to introduce ourselves.",
      intel:"Cold-emailed 6/5 ('edmonds framing sub'). Likely home office." }
  ]
};
